Pages/Categories.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ProjektSpotkaniaGrupTematycznych.Data;
using ProjektSpotkaniaGrupTematycznych.Models;

namespace ProjektSpotkaniaGrupTematycznych.Pages
{
    [Authorize]
    public class CategoriesModel : PageModel
    {
        private readonly ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext _context;

        public CategoriesModel(ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Category> Category { get;set; }

        public async Task OnGetAsync()
        {
            Category = await _context.Category.ToListAsync();
        }
    }
}

Pages/CreateCategory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjektSpotkaniaGrupTematycznych.Data;
using ProjektSpotkaniaGrupTematycznych.Models;

namespace ProjektSpotkaniaGrupTematycznych.Pages
{
    public class CreateCategoryModel : PageModel
    {
        private readonly ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext _context;

        public CreateCategoryModel(ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Category Category { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Category.Add(Category);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Categories");
        }
    }
}

Pages/CreateGroup.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using ProjektSpotkaniaGrupTematycznych.Data;
using ProjektSpotkaniaGrupTematycznych.Models;


namespace ProjektSpotkaniaGrupTematycznych.Pages
{
    [Authorize]
    public class CreateGroupModel : PageModel
    {
        private readonly ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public CreateGroupModel(ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Group Group { get; set; }
        [BindProperty]
        public List<Category> Categories
        {
            get
            {
                var categories = _context.Category.ToList();
                List<Category> temp = new List<Category>();
                temp.Add(new Category());
                foreach (var x in categories)
                {
                    temp.Add(x);
                }
                return temp;
            }
            set { }
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {    
            if (!ModelState.IsValid)
            {
                System.Diagnostics.Debug.WriteLine(JsonSerializer.Serialize(ModelState));
                return Page();
            }

            if (_context.Group.Where(m => m.OwnerID == _userManager.GetUserId(User)).Count() >= 10) //tutaj ma sie odwolywac do appsettings
            {
                TempData["errorMessage"] = "Maksymalna liczba grup 10!";
                return Page(); // i tutaj jaks wiadomosc
            }

                
            if (Group.GroupCategoryId == null || Group.GroupCategoryId == 0)
            {
                Group.GroupCategory = null;
                Group.GroupCategoryId = null;
            }
            else
            {
                Group.GroupCategory = await _context.Category.FirstOrDefaultAsync(x => x.Id == Group.GroupCategoryId);
                /*foreach (var x in Categories)
                {
                    if (Group.GroupCategoryId == x.Id)
                        Group.GroupCategory = x;
                }*/
            }
            
            Group.OwnerID = _userManager.GetUserId(HttpContext.User);


            _context.Group.Add(Group);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Groups");
        }
    }
}

Pages/DeleteCategory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ProjektSpotkaniaGrupTematycznych.Data;
using ProjektSpotkaniaGrupTematycznych.Models;

namespace ProjektSpotkaniaGrupTematycznych.Pages
{
    [Authorize]
    public class DeleteCategoryModel : PageModel
    {
        private readonly ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext _context;

        public DeleteCategoryModel(ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category = await _context.Category.FirstOrDefaultAsync(m => m.Id == id);

            if (Category == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category = await _context.Category.FindAsync(id);
            var Group = _context.Group.Where(b => b.GroupCategoryId == id).ToList();

            if (Category != null)
            {
                _context.Category.Remove(Category);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Categories");
        }
    }
}

Pages/DeleteGroup.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ProjektSpotkaniaGrupTematycznych.Data;
using ProjektSpotkaniaGrupTematycznych.Models;

namespace ProjektSpotkaniaGrupTematycznych.Pages
{
    [Authorize]
    public class DeleteGroupModel : PageModel
    {
        private readonly ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext _context;

        public DeleteGroupModel(ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Group Group { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Group = await _context.Group.FirstOrDefaultAsync(m => m.Id == id);

            if (Group == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Group = await _context.Group.FindAsync(id);

            if (Group != null)
            {
                _context.Group.Remove(Group);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Groups");
        }
    }
}

Pages/DetailsGroup.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ProjektSpotkaniaGrupTematycznych.Data;
using ProjektSpotkaniaGrupTematycznych.Models;
using System.Text.Json;
using Microsoft.AspNetCore.Identity;


namespace ProjektSpotkaniaGrupTematycznych.Pages
{
    public class DetailsGroupModel : PageModel
    {
        private readonly ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DetailsGroupModel(ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public Group Group { get; set; }
        public IdentityUser GroupOwner { get; set; }
        public IList<IdentityUser> Invokers { get; set; }
        public IList<InvitationRequest> InvitationRequests { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Group = await _context.Group.Include( g => g.Members).ThenInclude(y => y.User).Include(group => group.Meetings).ThenInclude(z => z.Participants).FirstOrDefaultAsync(m => m.Id == id);
            if (Group == null)
                return NotFound();

            //_context.Entry(Group).Collection(b => b.Members).Load(); //load dependecies
            //Group.Members = await _context.Application
            
            Group.GroupCategory = await _context.Category.FirstOrDefaultAsync(m => m.Id == Group.GroupCategoryId);
            GroupOwner = await _context.Users.FirstOrDefaultAsync(m => m.Id == Group.OwnerID);
            InvitationRequests = await _context.InvitationRequest.Where(entity => entity.GroupID == Group.Id).ToListAsync();
            Invokers = await _context.Users.ToArrayAsync();
            
            return Page();
        }
        public bool IsInMeeting(Meeting meeting, string userID)
        {
            if (_context.UserMeeting.Where(p => p.MeetingId == meeting.Id && p.UserId == userID).Count() > 0)
                return true;
            return false;
        }
        public bool IsInGroup(string userID, int groupID)
        {
            if (_context.UserGroups.Where(p => p.UserId == userID && p.GroupId == groupID).Count() > 0)
                return true;
            return false;
        }
    }
}

Pages/EditCategory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjektSpotkaniaGrupTematycznych.Data;
using ProjektSpotkaniaGrupTematycznych.Models;

namespace ProjektSpotkaniaGrupTematycznych.Pages
{
    [Authorize]
    public class EditCategoryModel : PageModel
    {
        private readonly ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext _context;

        public EditCategoryModel(ProjektSpotkaniaGrupTematycznych.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category = await _context.Category.FirstOrDefaultAsync(m => m.Id == id);

            if (Category == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Category).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoryExists(Category.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Categories");
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

Pages/Enlist.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ProjektSpotkaniaGrupTematycznych.Data;
using ProjektSpotkaniaGrupTematycznych.Models;

namespace ProjektSpotkaniaGrupTematycznych.Pages
{
    [Authorize]
    public class EnlistModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        [BindProperty]
        public InvitationRequest InvRequest { get; set; }

        public EnlistModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [BindProperty]
        public Group Group { get; set; }
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Group = await _context.Group.FirstOrDefaultAsync(m => m.Id == id);

            if (Group == null)
            {
                return NotFound();
            }



            if (Group.OwnerID == _userManager.GetUserId(HttpContext.User))
                return RedirectToPage("./Groups");

            return Page();
        }
        public async Task<IActionResult> OnGetRetryAsync(int? id, bool retrybool)
        {
            if (id == null)
            {
                return NotFound();
            }

            Group = await _context.Group.FirstOrDefaultAsync(m => m.Id == id);

            if (Group == null)
            {
                return NotFound();
            }
            if (Group.OwnerID == _userManager.GetUserId(HttpContext.User))
                return RedirectToPage("./Groups");

            return Page();
        }
        public async Task<IActionResult> OnPostAsync(int? id, bool retrybool)
        {
            System.Diagnostics.Debug.WriteLine(retrybool);
            if (id == null)
            {
                return NotFound();
            }

            Group = await _context.Group.FindAsync(id);

            if (Group == null)
            {
                //jakis tempdata ze jest error
                return NotFound();
            }
            var userId = _userManager.GetUserId(HttpContext.User);

            if (_context.UserGroups.Where(p => p.GroupId == (int)id && p.UserId == userId).ToList().Count >= 1)
                return Page(); //juz jest w grupie

            if(retrybool == true)
            {
                var _invr = _context.InvitationRequest.Where(p => p.InvokerId == userId && p.GroupID == (int)id && p.Status == InvitationStatus.Declined).ToList(); //istnieje juz taki request
                InvRequest.Status = InvitationStatus.Pending;

            }
            else
            {
                var _inv = _context.InvitationRequest.Where(p => p.InvokerId == userId && p.GroupID == (int)id && p.Status == InvitationStatus.Pending).ToList(); //istnieje juz taki request
                if (_inv.Count > 0)
                {
                    //error message
                    return Page();
                }
            }
            
            InvRequest.GroupID = (int)id;
            InvRequest.RequestDate = DateTime.Now;
            InvRequest.InvokerId = userId;
            InvRequest.Status = InvitationStatus.Pending;

            if (retrybool == true)
            {
                System.Diagnostics.Debug.WriteLine(JsonSerializer.Serialize(InvRequest));

                _context.Attach(InvRequest).State = EntityState.Modified;
            }
            else
            {
                _context.InvitationRequest.Add(InvRequest);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToPage("./Groups");


            //return Page();
        }
    }
}

Pages/Categories.cshtml
@page
@model ProjektSpotkaniaGrupTematycznych.Pages.CategoriesModel

@{
    ViewData["Title"] = "Categories";
}

<h1>Categories</h1>

<p>
    <a asp-page="CreateCategory">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category[0].CategoryName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Category) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                <a asp-page="./EditCategory" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./DeleteCategory" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Pages/CreateCategory.cshtml
@page
@model ProjektSpotkaniaGrupTematycznych.Pages.CreateCategoryModel

@{
    ViewData["Title"] = "CreateCategory";
}

<h1>CreateCategory</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category.CategoryName" class="control-label"></label>
                <input asp-for="Category.CategoryName" class="form-control" />
                <span asp-validation-for="Category.CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Categories">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/CreateGroup.cshtml
@page
@model ProjektSpotkaniaGrupTematycznych.Pages.CreateGroupModel

@{
    ViewData["Title"] = "CreateGroup";
 
}

<h1>CreateGroup</h1>

<h4>Group </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Group.GroupName" class="control-label"></label>
                <input asp-for="Group.GroupName" class="form-control" />
                <span asp-validation-for="Group.GroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group.GroupDescription" class="control-label"></label>
                <input asp-for="Group.GroupDescription" class="form-control" />
                <span asp-validation-for="Group.GroupDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group.City" class="control-label"></label>
                <input asp-for="Group.City" class="form-control" />
                <span asp-validation-for="Group.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group.GroupCategoryId" class="control-label"></label>
                <select asp-for="Group.GroupCategoryId">
                    @foreach (var x in Model.Categories)
                    {
                        <option value="@x.Id">@x.CategoryName</option>
                    }
                </select>
            </div>
            @if (TempData["errorMessage"] != null)
            {
               <div class="form-group">
                   <span class="text-danger">@TempData["errorMessage"]</span>
               </div>
            }

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="/Groups">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/DeleteCategory.cshtml
@page
@model ProjektSpotkaniaGrupTematycznych.Pages.DeleteCategoryModel

@{
    ViewData["Title"] = "DeleteCategory";
}

<h1>DeleteCategory</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Category.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Categories">Back to List</a>
    </form>
</div>

Pages/DeleteGroup.cshtml
@page
@model ProjektSpotkaniaGrupTematycznych.Pages.DeleteGroupModel

@{
    ViewData["Title"] = "DeleteGroup";
}

<h1>DeleteGroup</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Group.GroupName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Group.GroupName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Group.GroupDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Group.GroupDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Group.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Group.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Group.OwnerID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Group.OwnerID)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Group.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Groups">Back to List</a>
    </form>
</div>

Pages/EditCategory.cshtml
@page
@model ProjektSpotkaniaGrupTematycznych.Pages.EditCategoryModel

@{
    ViewData["Title"] = "EditCategory";
}

<h1>EditCategory</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Category.Id" />
            <div class="form-group">
                <label asp-for="Category.CategoryName" class="control-label"></label>
                <input asp-for="Category.CategoryName" class="form-control" />
                <span asp-validation-for="Category.CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Categories">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/EditGroup.cshtml
@page
@model ProjektSpotkaniaGrupTematycznych.Pages.EditGroupModel

@{
    ViewData["Title"] = "EditGroup";
}

<h1>EditGroup</h1>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Group.Id" />
            <div class="form-group">
                <label asp-for="Group.GroupName" class="control-label"></label>
                <input asp-for="Group.GroupName" class="form-control" />
                <span asp-validation-for="Group.GroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group.GroupDescription" class="control-label"></label>
                <input asp-for="Group.GroupDescription" class="form-control" />
                <span asp-validation-for="Group.GroupDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group.City" class="control-label"></label>
                <input asp-for="Group.City" class="form-control" />
                <span asp-validation-for="Group.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group.GroupCategoryId" class="control-label"></label>
                <select asp-for="Group.GroupCategoryId">
                    @foreach (var x in Model.Categories)
                    {
                        <option value="@x.Id">@x.CategoryName</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Groups">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Groups.cshtml
@page
@model ProjektSpotkaniaGrupTematycznych.Pages.GroupsModel

@{
    ViewData["Title"] = "Groups";
}
@using Microsoft.AspNetCore.Identity
@using ProjektSpotkaniaGrupTematycznych.Models;

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<h1>Groups</h1>

<p>
    <a asp-page="/CreateGroup">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Group[0].GroupName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Group[0].City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Group[0].GroupCategory)
            </th>
            <th>
                <a>Action</a>    
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Group)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupCategory.CategoryName)
                </td>
                <td>
                    <a asp-page="./DetailsGroup" asp-route-id="@item.Id">Details</a> |
                    @if (UserManager.GetUserId(User) == item.OwnerID)
                    {
                        <a asp-page="./EditGroup" asp-route-id="@item.Id">Edit</a>
                        <a> | </a>
                        <a asp-page="./DeleteGroup" asp-route-id="@item.Id">Delete</a>
                    }
                    else
                    {
                        bool check = false;
                        if (Model.InvRequests != null)
                        {
                            foreach (var x in Model.InvRequests)
                            {
                                if (item.Id == x.GroupID)
                                {
                                    check = true;
                                    if (x.Status == InvitationStatus.Accepted)
                                    {
                                    <a style="color:yellowgreen">Joined</a>
                                        check = true;
                                        break;
                                    }
                                    else if (x.Status == InvitationStatus.Pending)
                                    {
                                    <a style="color:cornflowerblue">Invitation Pending</a>
                                        check = true;
                                        break;
                                    }
                                    else if (x.Status == InvitationStatus.Declined)
                                    {
                                    <a style="color:red">Invitation Declined</a>
                                    <a> | </a>
                                    <a style="color:cornflowerblue" asp-page="./Enlist" asp-route-id="@item.Id" asp-route-retrybool="@true" asp-page-handler="Retry">Retry!</a>
                                        check = true;
                                        break;
                                    }
                                }
                            }
                        }
                        if(!check)
                        {
                            <a asp-page="./Enlist" asp-route-id="@item.Id">Become a member!</a>
                        }
                        
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="sidebar sticky">
    <form class="col-md-6" method="post">
        <div class="center" style="width:max-content">
            <input class="form-control" placeholder="Search by category" type="text" asp-for="CategoryName" />
        </div>
        <div class="center" style="width:max-content">
            <input class="form-control" placeholder="Search by city" type="text" asp-for="CityName" />
        </div>
        <div class="center" style="width:max-content">
            <input class="form-control" placeholder="Search by group name" type="text" asp-for="GroupName" />
        </div>
        <div class="center" style="width:max-content">
            <input type="submit" value="Search" />
            </div>
    </form>
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>